---
- name: Standalone create local directories for data
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ gp_user }}"
    group: "{{ gp_group }}"
    mode: '0700'
  loop:
    - "{{ gp_master_data_dir }}"
    - "{{ gp_segment_data_dir }}/demo1"
    - "{{ gp_segment_data_dir }}/demo2"

- name: Standalone generate the gpinitsystem configuration file
  ansible.builtin.template:
    src: gpinitsystem_standalone.j2
    dest: "/home/{{ gp_user }}/gpinitsystem_config"
    owner: "{{ gp_user }}"
    group: "{{ gp_group }}"

- name: Standalone initialize the single instance
  ansible.builtin.command: >
    gpinitsystem -a -c /home/{{ gp_user }}/gpinitsystem_config
  become: true
  become_user: "{{ gp_user }}"
  args:
    creates: "{{ gp_master_data_dir }}/gpseg-1"