---
- name: Create gpadmin group
  ansible.builtin.group:
    name: "{{ gp_group }}"
    state: present

- name: Create gpadmin user
  ansible.builtin.user:
    name: "{{ gp_user }}"
    group: "{{ gp_group }}"
    shell: /bin/bash
    generate_ssh_key: true
    ssh_key_bits: 2048
    create_home: true

- name: Configure sysctl parameters
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  loop:
    - { key: 'kernel.shmmax', value: '500000000' }
    - { key: 'kernel.shmall', value: '4000000000' }
    - { key: 'vm.overcommit_memory', value: '2' }
    - { key: 'net.ipv4.ip_local_port_range', value: '10000 65535' }

- name: Ensure SSH server is enabled and started
  ansible.builtin.service:
    name: "{{ 'ssh' if ansible_os_family == 'Debian' else 'sshd' }}"
    state: started
    enabled: true