---
- name: Prepare nodes
  hosts: all
  gather_facts: true
  tasks:
    - name: Install prerequisite packages (RHEL family)
      ansible.builtin.dnf:
        name:
          - openssh-clients
          - openssh-server
          - sudo
          - python3
        state: present
        update_cache: true
      when: ansible_facts['pkg_mgr'] in ['dnf', 'dnf5', 'yum']

    - name: Install prerequisite packages (Debian family)
      ansible.builtin.apt:
        name:
          - openssh-client
          - openssh-server
          - sudo
          - python3
        state: present
        update_cache: true
      when: ansible_facts['pkg_mgr'] == 'apt'
